# Site settings
title: Halton Xu 
email: halton.xu@gmail.com
descriptio: coder
#baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.halton.cc" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
disqus_shortname: ihalton 
